[project]
name = 'Autonomous-Insurance-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.claim-processing]
path = 'contracts/claim-processing.clar'
clarity_version = 2
epoch = 2.5

[contracts.insurance-policy]
path = 'contracts/insurance-policy.clar'
clarity_version = 2
epoch = 2.5

[contracts.insurance-pool]
path = 'contracts/insurance-pool.clar'
clarity_version = 2
epoch = 2.5

[contracts.oracle]
path = 'contracts/oracle.clar'
clarity_version = 2
epoch = 2.5

[contracts.risk-assessment]
path = 'contracts/risk-assessment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
